// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDate: typeof import('./src/components/AppDate.vue')['default']
    BaseButton: typeof import('./src/components/Button/BaseButton.vue')['default']
    'BaseButton.story': typeof import('./src/components/Button/BaseButton.story.vue')['default']
    Demo: typeof import('./src/components/Demo/Demo.vue')['default']
    'Demo.story': typeof import('./src/components/Demo/Demo.story.vue')['default']
    EventButton: typeof import('./src/components/Event/EventButton.vue')['default']
    'EventButton.story': typeof import('./src/components/Event/EventButton.story.vue')['default']
    ForumList: typeof import('./src/components/ForumList.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    Meow: typeof import('./src/components/Meow/Meow.vue')['default']
    'Meow.story': typeof import('./src/components/Meow/Meow.story.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    PageHome: typeof import('./src/components/PageHome.vue')['default']
    PostEditor: typeof import('./src/components/PostEditor.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreadList: typeof import('./src/components/ThreadList.vue')['default']
    ThreadShow: typeof import('./src/components/ThreadShow.vue')['default']
    Time: typeof import('./src/components/Time.vue')['default']
  }
}

export {}
